// Code generated by go generate; DO NOT EDIT.
// generated using files from resources directory
package box

func init() {
	resources.Add("/TestChainValidationMessageSuiteTestAccountActorCreationfailcreateBLSaccountactorinsufficientbalance", []byte{48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestAccountActorCreationfailcreateSECP256K1accountactorinsufficientbalance", []byte{48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestAccountActorCreationsuccesscreateBLSaccountactor", []byte{56, 55, 50, 10})
	resources.Add("/TestChainValidationMessageSuiteTestAccountActorCreationsuccesscreateSECP256K1accountactor", []byte{55, 53, 54, 10})
	resources.Add("/TestChainValidationMessageSuiteTestInitActorSequentialIDAddressCreate", []byte{49, 57, 49, 56, 10, 50, 48, 48, 53, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMessageApplicationEdgecasesabortduringactorexecution", []byte{49, 57, 49, 56, 10, 51, 52, 55, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMessageApplicationEdgecasesfailtocovergascostformessagereceiptonchain", []byte{48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMessageApplicationEdgecasesinvalidactorCallSeqNum", []byte{48, 10, 48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMessageApplicationEdgecasesnotenoughgastopaymessageonchainsizecost", []byte{48, 10, 48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMultiSigActoraddsigner", []byte{49, 57, 52, 50, 10, 49, 48, 54, 10, 49, 50, 49, 50, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMultiSigActorconstructortest", []byte{49, 56, 53, 49, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMultiSigActorproposeandapprove", []byte{50, 48, 51, 55, 10, 56, 57, 53, 10, 50, 50, 50, 10, 49, 54, 56, 10, 49, 48, 50, 55, 10})
	resources.Add("/TestChainValidationMessageSuiteTestMultiSigActorproposeandcancel", []byte{50, 48, 51, 55, 10, 56, 57, 53, 10, 50, 50, 50, 10, 52, 51, 56, 10})
	resources.Add("/TestChainValidationMessageSuiteTestNestedSendsokbasicsend", []byte{})
	resources.Add("/TestChainValidationMessageSuiteTestPaychhappypathcollect", []byte{49, 57, 49, 56, 10, 51, 50, 48, 10, 49, 57, 49, 10, 50, 51, 54, 10})
	resources.Add("/TestChainValidationMessageSuiteTestPaychhappypathconstructor", []byte{49, 57, 49, 56, 10})
	resources.Add("/TestChainValidationMessageSuiteTestPaychhappypathupdate", []byte{49, 57, 49, 56, 10, 51, 49, 56, 10})
	resources.Add("/TestChainValidationMessageSuiteTestValueTransferSimplefailtotransfermorefundsthansenderbalance0", []byte{48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestValueTransferSimplefailtotransfermorefundsthansenderhaswhensenderbalancezero", []byte{48, 10})
	resources.Add("/TestChainValidationMessageSuiteTestValueTransferSimplesuccessfullytransferfundsfromsendertoreceiver", []byte{49, 50, 56, 10})
	resources.Add("/TestChainValidationMessageSuiteTestValueTransferSimplesuccessfullytransferzerofundsfromsendertoreceiver", []byte{49, 50, 52, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestBlockMessageDeduplicationapplyaduplicatedBLSmessage", []byte{49, 50, 56, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestBlockMessageDeduplicationapplyasingleBLSmessage", []byte{49, 50, 56, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestBlockMessageDeduplicationapplyasingleSECPmessage", []byte{49, 51, 52, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestBlockMessageDeduplicationapplyduplicateSECPmessage", []byte{49, 51, 52, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestInvalidSenderAddressmessagesenderaddressisdefinedbutnotinstatetree", []byte{48, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestMinerMissPoStChallengeWindow", []byte{51, 48, 53, 51, 10, 49, 50, 50, 55, 10, 49, 49, 53, 51, 10, 51, 49, 50, 57, 10, 50, 48, 56, 49, 10, 56, 52, 50, 56, 10, 49, 50, 52, 10})
	resources.Add("/TestChainValidationTipSetSuiteTestMinerSubmitFallbackPoSt", []byte{51, 48, 53, 51, 10, 49, 50, 50, 55, 10, 49, 49, 53, 51, 10, 51, 49, 50, 57, 10, 50, 48, 56, 49, 10, 56, 52, 50, 56, 10, 50, 51, 50, 49, 10, 49, 50, 52, 10})
}
